server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: python-logger
    static_configs:
      - targets: [localhost]
        labels:
          job: python-logger
          __path__: /app/logs/*.log

    # Optional: read from top on first discovery
    # start_position: beginning

    pipeline_stages:
      - regex:
          # Use single quotes to avoid YAML escaping issues
          expression: '

\[WorkflowID: (?P<workflow_id>[a-f0-9-]+)\]

'
      - labels:
          workflow_id:
